### ISSUE TITLE
Server Offline

### ISSUE THREAD

**Issue by getSono** [ImExoOdeex/ismcserveronline#10]
My server `mc.sono.is-a.dev` shows on `ismcserver.online` that the server is offline, but is online??

**Comment by ImExoOdeex** [comment]
Hi, Your server doesn't send player counts back and API does not set fallback values for those, so it crashes. I will fix that within some time, thanks!

**Comment by ImExoOdeex** [comment]
hey, I've pushed a fix, thank you for this report 🎉❤️
