### ISSUE TITLE
Updates not working

### ISSUE THREAD

**Issue by PREXcerberus** [ImExoOdeex/ismcserveronline#6]
everytime i update the online parameters. its all fine, the second I add the offline parameters, it moves it over to the "online" section, and turns the offline section back to default, its like somebody deleted all the info from online, and replaced it with the offline info. I've tried reinviting and what not but nothing seems to fix it, i tried a different browser, same issue

**Comment by PREXcerberus** [comment]
![image_2024-04-07_170350970](https://github.com/ImExoOdeex/ismcserveronline/assets/83886939/ffdd6af3-2fab-4638-ab4b-d7d063934487)
![image](https://github.com/ImExoOdeex/ismcserveronline/assets/83886939/b6d791af-1c50-4a01-829c-81a418221b43)

**Comment by ImExoOdeex** [comment]
hey, thanks for letting us know! This issue has been fixed. Please make sure to update custom messages again.

**Comment by PREXcerberus** [comment]
legend! We appreciate your work!
